global using AuthService.Shared.guid;
global using System.Threading.Tasks;
global using Microsoft.AspNetCore.Authorization;
global using Microsoft.AspNetCore.Http;
global using Microsoft.AspNetCore.Mvc;
global using Ardalis.ApiEndpoints;
global using MediatR;
global using AuthService.Shared.Claims;
global using AuthService.Shared.Exceptions;